/home: 
  controller: "HomeController"
  action: "showPage"
  method: "GET"
/login:
  controller: 'Auth\LoginController'
  action: 'showForm'
  method: 'GET'
/auth:
  controller: 'Auth\LoginController'
  action: 'auth'
  method: 'POST'
/registration:
  controller: 'Auth\RegisterController'
  action: 'showForm'
  method: 'GET'
/register:
  controller: 'Auth\RegisterController'
  action: 'auth'
  method: 'POST'
/forgot:
  controller: 'Auth\ForgotPasswordController'
  action: 'showForm'
  method: 'GET'
/confirmation:
  controller: 'Auth\ForgotPasswordController'
  action: 'confirmation'
  method: 'POST'
/code_confirmation:
  controller: 'Auth\ForgotPasswordController'
  action: 'codeConfirmation'
  method: 'POST'
/settings:
  controller: 'SettingsController'
  action: 'show'
  method: 'GET'
/account:
  controller: 'AccountController'
  action: 'show'
  method: 'GET'
/edit-account:
  controller: 'AccountController'
  action: 'updateDefaultInfo'
  method: 'POST'
/update-social-links:
  controller: 'AccountController'
  action: 'updateSocialLinks'
  method: 'POST'
/update-user-settings:
  controller: 'SettingsController'
  action: 'updateSettings'
  method: 'POST'